apiVersion: apps/v1
kind: Deployment
metadata:
  name: joga-bonito-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joga-bonito-gke
  template:
    metadata:
      labels:
        app: joga-bonito-gke
    spec:
      containers:
        - name: joga-bonito-gke
          image: gcr.io/${PROJECT_ID}/joga-bonito-gke:latest
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: joga-bonito-gke-service
spec:
  selector:
    app: joga-bonito-gke
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer